# Generated by Django 2.2.7 on 2022-01-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя ПМ-а')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия ПМ-а')),
            ],
            options={
                'verbose_name': 'ПМ',
                'verbose_name_plural': 'ПМ-ы',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наменование проекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание проекта')),
                ('start', models.DateField(verbose_name='Дата с')),
                ('end', models.DateField(verbose_name='Дата по')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='StudentLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Навык ученика')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя ученика')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия ученика')),
                ('is_in_team', models.BooleanField(default=False, verbose_name='Распределен в команду?')),
                ('student_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.StudentLevels', verbose_name='Уровень ученика')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Намнование команды')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Projects', verbose_name='Проект')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.ProjectManagers', verbose_name='ПМ')),
            ],
            options={
                'verbose_name': 'Команда проекта',
                'verbose_name_plural': 'Команды проектов',
            },
        ),
        migrations.CreateModel(
            name='StudentsWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_from', models.TimeField(verbose_name='Созвон с')),
                ('works_to', models.TimeField(verbose_name='Созвон по')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Projects', verbose_name='Проект')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Students', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Время созвона студента',
                'verbose_name_plural': 'Время созвона студента',
            },
        ),
        migrations.CreateModel(
            name='StudentsToCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Students', verbose_name='Cтудент')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Студент в команде',
                'verbose_name_plural': 'Студенты в команде',
            },
        ),
        migrations.CreateModel(
            name='PMWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_from', models.TimeField(verbose_name='Работает с')),
                ('works_to', models.TimeField(verbose_name='Работает по')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Projects', verbose_name='Проект')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.ProjectManagers', verbose_name='ПМ')),
            ],
            options={
                'verbose_name': 'Часы работы ПМ',
                'verbose_name_plural': 'Часы работы ПМ',
            },
        ),
    ]
