# Generated by Django 2.2.7 on 2022-01-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstocommands',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Students', verbose_name='Cтудент'),
        ),
    ]
